<a href="https://colab.research.google.com/github/anmolkumar0717/pyTorch/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello")

hello


In [3]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.2.1+cu121


In [5]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
scaler.item()

7

In [8]:
#vector

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:

#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX.ndim

2

In [14]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [3,2,4]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 4, 5],
         [3, 2, 4]]])

In [15]:
TENSOR.shape


torch.Size([1, 3, 3])

In [16]:
a=torch.tensor([[[[[[[[[[[[[1,2,3,4],
 [8,9,9,8]]]]]]]]]]]]])
a

tensor([[[[[[[[[[[[[1, 2, 3, 4],
                   [8, 9, 9, 8]]]]]]]]]]]]])

In [17]:
a.shape


torch.Size([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4])

In [18]:
a.ndim

13

### Create a random tensor

In [19]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4200, 0.8528, 0.2828, 0.4459],
        [0.4598, 0.9486, 0.1943, 0.4973],
        [0.9812, 0.9386, 0.4551, 0.5352]])

In [20]:
# create a randome tensor with similar shape to an image tensor
randome_image_size_tensor=torch.rand(size=(3,224,224))
print(randome_image_size_tensor.shape,"dimension = ",randome_image_size_tensor.ndim)

torch.Size([3, 224, 224]) dimension =  3


In [21]:
random_tensor1=torch.rand(3,4,3)
print(random_tensor1)
print(random_tensor1.ndim)

tensor([[[0.5979, 0.2102, 0.3922],
         [0.6123, 0.1597, 0.8504],
         [0.3103, 0.2107, 0.3327],
         [0.6561, 0.8791, 0.3039]],

        [[0.8730, 0.4067, 0.9417],
         [0.9427, 0.7938, 0.6641],
         [0.5908, 0.7166, 0.4009],
         [0.1338, 0.3194, 0.3699]],

        [[0.0362, 0.4561, 0.3255],
         [0.6526, 0.3623, 0.0158],
         [0.1124, 0.1033, 0.0883],
         [0.3632, 0.5037, 0.9401]]])
3


### Zeros and Ones Tensor

In [22]:
zeros=torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zeros*random_tensor1

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [24]:
#creating a tensor of all ones
ones=torch.ones(size=(3,3,2,3,4))
ones

tensor([[[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

         

In [25]:
ones.dtype

torch.float32

### creating a range of ternsors and tensor_like

In [26]:
#use torch .rande()
one_2_ten=torch.arange(2,11,3)
one_2_ten

tensor([2, 5, 8])

In [27]:
#creating tensors like

ten_zeros=torch.zeros_like(input=one_2_ten)
ten_zeros

tensor([0, 0, 0])

In [28]:
ten_one=torch.ones_like(input=ten_zeros)
ten_one

tensor([1, 1, 1])

### tensor Data type

In [29]:
#float 32 tensor
float_32_tensor=torch.tensor([1,2,3,3,423],
                             dtype=torch.float16,
                             device="cpu",
                             requires_grad=False)
float_32_tensor

tensor([  1.,   2.,   3.,   3., 423.], dtype=torch.float16)

In [30]:
unsinged_integer=torch.tensor([1,2,3,4,5,67,8],
                              dtype=torch.uint8,
                              device='cpu',
                              requires_grad=False)
unsinged_integer

tensor([ 1,  2,  3,  4,  5, 67,  8], dtype=torch.uint8)

In [31]:
unsinged_integer.dtype

torch.uint8

In [32]:
one_ten=torch.ones_like(input=torch.arange(0,10))
one_ten

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
tensor_16_float=torch.tensor([1,2,32,430],
                            dtype=torch.float16,
                            device=None,
                            requires_grad=False
                            )

In [34]:
tensor_32_float=torch.tensor([1,2,32,430],
                            dtype=torch.float32,
                            device=None,
                            requires_grad=False
                            )

In [35]:
tensor_16_float*tensor_32_float

tensor([1.0000e+00, 4.0000e+00, 1.0240e+03, 1.8490e+05])

In [36]:
integer_tensor=torch.tensor([1,23,2,212],
                            dtype=torch.int32)

In [37]:
integer_tensor*tensor_16_float

tensor([ 1., 46., 64., inf], dtype=torch.float16)

In [38]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4981, 0.4786, 0.9602, 0.6382],
        [0.3106, 0.8998, 0.8778, 0.0360],
        [0.4294, 0.6778, 0.0694, 0.6343]])

In [39]:
some_tensor=some_tensor.type(torch.float16)

In [40]:
print(f"Data Type of the tensor is:-{some_tensor.dtype}")
print(f"Device of the Tensor is :-{some_tensor.device}")
print(f"Size of the tensor:-{some_tensor.size()}")
print(f"Dimension of the tensor is:-{some_tensor.ndim}")

Data Type of the tensor is:-torch.float16
Device of the Tensor is :-cpu
Size of the tensor:-torch.Size([3, 4])
Dimension of the tensor is:-2


In [41]:
device=torch.device("cuda")

In [42]:
#error because we are using cpu insted of gpu "cuda is a gpu device not a cpu device"

some_tensor=some_tensor.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
some_tensor.device

In [43]:
#matrix multiplocation
%%time
mat1=torch.tensor([[1,2,3],
                   [2,3,4]])
mat2=torch.tensor([[2,3,4],
                   [3,5,6],
                   [43,34,4]])

torch.matmul(mat1,mat2)


CPU times: user 1.46 ms, sys: 0 ns, total: 1.46 ms
Wall time: 2.26 ms


tensor([[137, 115,  28],
        [185, 157,  42]])

In [44]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [49]:
#to find the positon of the min element in the tensor
x.argmin()

tensor(0)

In [48]:
#to find the positon of the min element in the tensor
x.argmax()

tensor(9)

In [53]:
#Stacking :-
#1.vstack(verical stack):-it add the second tensor in vericaly

tensor1=torch.tensor([[1,2,3,4],
                      [5,3,2,1],
                      [3,3,2,1]]
                     )
tensor2=torch.tensor([[2,3,4,5],
                      [6,7,7,8],
                      [9,3,21,1],
                      [2,3,1,3]]
                     )
torch.vstack((tensor1,tensor2))

tensor([[ 1,  2,  3,  4],
        [ 5,  3,  2,  1],
        [ 3,  3,  2,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  7,  8],
        [ 9,  3, 21,  1],
        [ 2,  3,  1,  3]])

In [54]:
#Hstack(horizontal stack):-To add the second tensor in the horizontal direction
tensor3=torch.tensor([[5,4,3,1],
                      [3,4,5,6]])

tensor4=torch.tensor([[4,3,5,12],
                      [4,5,6,7]])

torch.hstack((tensor3,tensor4))

tensor([[ 5,  4,  3,  1,  4,  3,  5, 12],
        [ 3,  4,  5,  6,  4,  5,  6,  7]])