<a href="https://colab.research.google.com/github/anmolkumar0717/pyTorch/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
print("hello")

hello


In [78]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [79]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.2.1+cu121


In [80]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [81]:
scaler.ndim

0

In [82]:
scaler.item()

7

In [83]:
#vector

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [84]:
vector.ndim

1

In [85]:
vector.shape

torch.Size([2])

In [86]:

#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [87]:
MATRIX.shape

torch.Size([2, 2])

In [88]:
MATRIX.ndim

2

In [89]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [3,2,4]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 4, 5],
         [3, 2, 4]]])

In [90]:
TENSOR.shape


torch.Size([1, 3, 3])

In [91]:
a=torch.tensor([[[[[[[[[[[[[1,2,3,4],
 [8,9,9,8]]]]]]]]]]]]])
a

tensor([[[[[[[[[[[[[1, 2, 3, 4],
                   [8, 9, 9, 8]]]]]]]]]]]]])

In [92]:
a.shape


torch.Size([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4])

In [93]:
a.ndim

13

### Create a random tensor

In [94]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1499, 0.0652, 0.5901, 0.2584],
        [0.0911, 0.5484, 0.1068, 0.3594],
        [0.9693, 0.3671, 0.1273, 0.7978]])

In [95]:
# create a randome tensor with similar shape to an image tensor
randome_image_size_tensor=torch.rand(size=(3,224,224))
print(randome_image_size_tensor.shape,"dimension = ",randome_image_size_tensor.ndim)

torch.Size([3, 224, 224]) dimension =  3


In [96]:
random_tensor1=torch.rand(3,4,3)
print(random_tensor1)
print(random_tensor1.ndim)

tensor([[[0.3476, 0.2838, 0.8584],
         [0.3513, 0.7813, 0.2531],
         [0.3571, 0.2523, 0.9531],
         [0.4362, 0.6242, 0.0281]],

        [[0.2348, 0.4071, 0.8446],
         [0.2554, 0.0972, 0.2751],
         [0.0640, 0.2022, 0.4571],
         [0.2307, 0.1363, 0.7514]],

        [[0.1359, 0.6515, 0.0773],
         [0.7275, 0.8269, 0.4231],
         [0.1474, 0.0798, 0.8431],
         [0.4616, 0.3638, 0.3426]]])
3


### Zeros and Ones Tensor

In [97]:
zeros=torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [98]:
zeros*random_tensor1

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [99]:
#creating a tensor of all ones
ones=torch.ones(size=(3,3,2,3,4))
ones

tensor([[[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

         

In [100]:
ones.dtype

torch.float32

### creating a range of ternsors and tensor_like

In [101]:
#use torch .rande()
one_2_ten=torch.arange(2,11,3)
one_2_ten

tensor([2, 5, 8])

In [102]:
#creating tensors like

ten_zeros=torch.zeros_like(input=one_2_ten)
ten_zeros

tensor([0, 0, 0])

In [103]:
ten_one=torch.ones_like(input=ten_zeros)
ten_one

tensor([1, 1, 1])

### tensor Data type

In [104]:
#float 32 tensor
float_32_tensor=torch.tensor([1,2,3,3,423],
                             dtype=torch.float16,
                             device="cpu",
                             requires_grad=False)
float_32_tensor

tensor([  1.,   2.,   3.,   3., 423.], dtype=torch.float16)

In [105]:
unsinged_integer=torch.tensor([1,2,3,4,5,67,8],
                              dtype=torch.uint8,
                              device='cpu',
                              requires_grad=False)
unsinged_integer

tensor([ 1,  2,  3,  4,  5, 67,  8], dtype=torch.uint8)

In [106]:
unsinged_integer.dtype

torch.uint8

In [107]:
one_ten=torch.ones_like(input=torch.arange(0,10))
one_ten

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [108]:
tensor_16_float=torch.tensor([1,2,32,430],
                            dtype=torch.float16,
                            device=None,
                            requires_grad=False
                            )

In [109]:
tensor_32_float=torch.tensor([1,2,32,430],
                            dtype=torch.float32,
                            device=None,
                            requires_grad=False
                            )

In [110]:
tensor_16_float*tensor_32_float

tensor([1.0000e+00, 4.0000e+00, 1.0240e+03, 1.8490e+05])

In [111]:
integer_tensor=torch.tensor([1,23,2,212],
                            dtype=torch.int32)

In [112]:
integer_tensor*tensor_16_float

tensor([ 1., 46., 64., inf], dtype=torch.float16)

In [113]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.7643, 0.5652, 0.2361, 0.3836],
        [0.1558, 0.6647, 0.7986, 0.9949],
        [0.2127, 0.3801, 0.7587, 0.5678]])

In [114]:
some_tensor=some_tensor.type(torch.float16)

In [115]:
print(f"Data Type of the tensor is:-{some_tensor.dtype}")
print(f"Device of the Tensor is :-{some_tensor.device}")
print(f"Size of the tensor:-{some_tensor.size()}")
print(f"Dimension of the tensor is:-{some_tensor.ndim}")

Data Type of the tensor is:-torch.float16
Device of the Tensor is :-cpu
Size of the tensor:-torch.Size([3, 4])
Dimension of the tensor is:-2


In [116]:
device=torch.device("cuda")

In [117]:
#error because we are using cpu insted of gpu "cuda is a gpu device not a cpu device"

some_tensor=some_tensor.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [118]:
some_tensor.device

device(type='cpu')

In [119]:
#matrix multiplocation
%%time
mat1=torch.tensor([[1,2,3],
                   [2,3,4]])
mat2=torch.tensor([[2,3,4],
                   [3,5,6],
                   [43,34,4]])

torch.matmul(mat1,mat2)


CPU times: user 1.29 ms, sys: 0 ns, total: 1.29 ms
Wall time: 1.2 ms


tensor([[137, 115,  28],
        [185, 157,  42]])

In [120]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [121]:
#to find the positon of the min element in the tensor
x.argmin()

tensor(0)

In [122]:
#to find the positon of the min element in the tensor
x.argmax()

tensor(9)

In [123]:
#respahing the tensor

#we have to take care about the dimension.when we change the shape we have to take care about its number of the elements

import torch
x=torch.arange(0.,24.)
print(x,x.shape)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]) torch.Size([24])


In [124]:
#respahing the tensor
x_reshaped=x.reshape(2,2,6)
x_reshaped

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.]],

        [[12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.]]])

In [125]:
#Changing the view

#it can't change the orignal

#if we changes z then x will changes because views shares same memory with the original tensor

z=x.view(2,6,2)
print(z)

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.],
         [18., 19.],
         [20., 21.],
         [22., 23.]]])


In [126]:
#here we changes the value of z and we observe that the memory of x automatically changes.
#they share same memory thats why when we change the monory of z ,x(original memory var) value also changes.

z[0][0][1]=9
print(x)

tensor([ 0.,  9.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])


In [127]:
#stack tensor on the top of each other
new_x=torch.tensor([[1,2,3],
                    [3,45,6],
                    [4,3,5]])

new_x.ndim

2

In [128]:
new_x_stacked=torch.stack([new_x],dim=-2)
new_x_stacked

tensor([[[ 1,  2,  3]],

        [[ 3, 45,  6]],

        [[ 4,  3,  5]]])

In [129]:
#Stacking :-
#1.vstack(verical stack):-it add the second tensor in vericaly

tensor1=torch.tensor([[1,2,3,4],
                      [5,3,2,1],
                      [3,3,2,1]]
                     )
tensor2=torch.tensor([[2,3,4,5],
                      [6,7,7,8],
                      [9,3,21,1],
                      [2,3,1,3]]
                     )
torch.vstack((tensor1,tensor2))

tensor([[ 1,  2,  3,  4],
        [ 5,  3,  2,  1],
        [ 3,  3,  2,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  7,  8],
        [ 9,  3, 21,  1],
        [ 2,  3,  1,  3]])

In [130]:
#Hstack(horizontal stack):-To add the second tensor in the horizontal direction
tensor3=torch.tensor([[5,4,3,1],
                      [3,4,5,6]])

tensor4=torch.tensor([[4,3,5,12],
                      [4,5,6,7]])

torch.hstack((tensor3,tensor4))

tensor([[ 5,  4,  3,  1,  4,  3,  5, 12],
        [ 3,  4,  5,  6,  4,  5,  6,  7]])

In [131]:
#torch.squeeze() - remove all the single dimension from a targert tensor

torch_noname=torch.zeros(2,1,2,1,3)
print(f"size of the tensor before squeez method{torch_noname}")
y=torch.squeeze(torch_noname)
print(f"size of the tensor before squeez method{y}")

size of the tensor before squeez methodtensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]])
size of the tensor before squeez methodtensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [132]:
y1=torch.squeeze(torch_noname,1)
print(f"before parameter{torch_noname,torch_noname.size()}")
print(f"y1 when parameter passes as 1 output will be {y1.size()}")

before parameter(tensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]]), torch.Size([2, 1, 2, 1, 3]))
y1 when parameter passes as 1 output will be torch.Size([2, 2, 1, 3])


In [133]:
y2=torch.squeeze(torch_noname,1)
print(f"y2 value when patameter is 0{y2.size()}")

y2 value when patameter is 0torch.Size([2, 2, 1, 3])


In [134]:
#torch.unsqueeze()- add one dimension at the a specific location in the targeted tensor

In [135]:
y_unsqueezed=y2.unsqueeze(dim=1)
print(f"before parameter{torch_noname,torch_noname.size()}")
print(f"The usqueezed tensor is {y_unsqueezed,y_unsqueezed.size()}")

before parameter(tensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]]), torch.Size([2, 1, 2, 1, 3]))
The usqueezed tensor is (tensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]]]]), torch.Size([2, 1, 2, 1, 3]))


In [136]:
y1=torch.zeros([2])
y2=y1.unsqueeze(dim=0)
y2.size()

torch.Size([1, 2])

In [145]:
#torch.permute()-rearranges the dimensions of a target tensor in a specified order

tensor_per=torch.ones([2,1,3,3])
print(f"before tensor is {tensor_per} size of the tensor is {tensor_per.size()}")
permuted_tensor=torch.permute(tensor_per,(2,3,0,1))
# in the above tensor the first dim is changes with the 2nd dim of the inintial tensor and the first dim is changes with the div 3 and the third tensor is changes with the zeroth dim vice varsa
print(f"permuted tensor is {permuted_tensor} size of the tensor is {permuted_tensor.size()}")


before tensor is tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]]) size of the tensor is torch.Size([2, 1, 3, 3])
permuted tensor is tensor([[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]]]) size of the tensor is torch.Size([3, 3, 2, 1])


In [153]:
tensor_indexing=torch.arange(1,10).reshape(1,3,3)
print(tensor_indexing)
tensor_indexing[0,0,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


tensor([1, 2, 3])

In [159]:
tensor_indexing[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
## TENSORS with NumPy Arrays

In [165]:
import numpy as np
array=np.arange(1.0,9.0)
print(f"array is {array} and type is {array.dtype}")
tensor_Arr=torch.from_numpy(array)
print(f"tensor using np array {tensor_Arr}")

array is [1. 2. 3. 4. 5. 6. 7. 8.] and type is float64
tensor using np array tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [168]:
# if we change the value of the array to something else then it cant effect the tensor
array=array+1
print(f"Array is {array}")
print(f"tensor ={tensor_Arr}")

Array is [ 4.  5.  6.  7.  8.  9. 10. 11.]
tensor =tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)


In [171]:
#tensor to Numpy

tensor=torch.zeros(1,3)
print(f"tensor dtype is {tensor.dtype}")
numpy_tensor=tensor.numpy()
print(f"the numpy tensor is {numpy_tensor} and the size of the numpy tensor is {numpy_tensor.dtype}")

tensor dtype is torch.float32
the numpy tensor is [[0. 0. 0.]] and the size of the numpy tensor is float32


In [172]:
tensor=tensor+1

print(tensor)

print(f"tensor after numpy{numpy_tensor}")


tensor([[1., 1., 1.]])
tensor after numpy[[0. 0. 0.]]


In [173]:
import torch
random_tensor1=torch.rand(3,4)
random_tensor2=torch.rand(3,4)
print(random_tensor1)
print(random_tensor2)
print(random_tensor1==random_tensor2)


tensor([[0.4123, 0.7159, 0.0056, 0.1741],
        [0.5983, 0.5871, 0.7925, 0.8658],
        [0.3615, 0.7136, 0.1072, 0.5294]])
tensor([[0.8188, 0.5387, 0.9651, 0.9084],
        [0.8819, 0.9061, 0.6123, 0.5950],
        [0.0984, 0.9437, 0.9700, 0.2915]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [184]:
# lets make some random but reproducible tensor
import torch

#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_a=torch.rand(3,4,6)
torch.manual_seed(RANDOM_SEED)
random_tensor_b=torch.rand(3,4,6)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)


tensor([[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895]],

        [[0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447],
         [0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958],
         [0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666]]])
tensor([[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994, 0.5472

tensor([[1, 2, 3]])