<a href="https://colab.research.google.com/github/anmolkumar0717/Alphabet/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.2.1+cu121


In [ ]:
#scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()

7

In [ ]:
#vector

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:

#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX.ndim

2

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [3,2,4]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 4, 5],
         [3, 2, 4]]])

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

In [ ]:
a=torch.tensor([[[[[[[[[[[[[1,2,3,4],
 [8,9,9,8]]]]]]]]]]]]])
a

tensor([[[[[[[[[[[[[1, 2, 3, 4],
                   [8, 9, 9, 8]]]]]]]]]]]]])

In [ ]:
a.size

<function Tensor.size>

In [ ]:
a.ndim

13

### Create a random tensor

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6593, 0.5775, 0.3083, 0.6823],
        [0.6373, 0.4214, 0.7987, 0.8675],
        [0.6499, 0.9844, 0.5052, 0.2253]])

In [ ]:
# create a randome tensor with similar shape to an image tensor
randome_image_size_tensor=torch.rand(size=(3,224,224))
print(randome_image_size_tensor.shape,"dimension = ",randome_image_size_tensor.ndim)

torch.Size([3, 224, 224]) dimension =  3


In [ ]:
random_tensor1=torch.rand(3,4,3)
print(random_tensor1)
print(random_tensor1.ndim)

tensor([[[0.0781, 0.1836, 0.4360],
         [0.9114, 0.5069, 0.8399],
         [0.9697, 0.7436, 0.2684],
         [0.0131, 0.9858, 0.8982]],

        [[0.4035, 0.8880, 0.9762],
         [0.2796, 0.3091, 0.3585],
         [0.7928, 0.5335, 0.8423],
         [0.4736, 0.6988, 0.7520]],

        [[0.6419, 0.4432, 0.5197],
         [0.2290, 0.6909, 0.2652],
         [0.6058, 0.4181, 0.1189],
         [0.4659, 0.6568, 0.3536]]])
3


### Zeros and Ones Tensor

In [ ]:
zeros=torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeros*random_tensor1

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
#creating a tensor of all ones
ones=torch.ones(size=(3,3,2,3,4))
ones

tensor([[[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],


         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],

         

In [ ]:
ones.dtype

torch.float32

### creating a range of ternsors and tensor_like

In [ ]:
#use torch .rande()
one_2_ten=torch.arange(2,11,3)
one_2_ten

tensor([2, 5, 8])

In [ ]:
#creating tensors like

ten_zeros=torch.zeros_like(input=one_2_ten)
ten_zeros

tensor([0, 0, 0])

In [ ]:
ten_one=torch.ones_like(input=ten_zeros)
ten_one

tensor([1, 1, 1])

### tensor Data type

In [ ]:
#float 32 tensor
float_32_tensor=torch.tensor([1,2,3,3,423],
                             dtype=torch.float16,
                             device="cpu",
                             requires_grad=False)
float_32_tensor

tensor([  1.,   2.,   3.,   3., 423.], dtype=torch.float16)

In [ ]:
unsinged_integer=torch.tensor([1,2,3,4,5,67,8],
                              dtype=torch.uint8,
                              device='cpu',
                              requires_grad=False)
unsinged_integer

tensor([ 1,  2,  3,  4,  5, 67,  8], dtype=torch.uint8)

In [ ]:
unsinged_integer.dtype

torch.uint8